import Head from 'next/head'
import NavigationBar from '../components/navigationBar';
import Intro from '../components/intro';
import Projects from '../components/projects';
import Skills from '../components/skills';
import About from '../components/about';
import Contact from '../components/contact';

const Home = () => {
  return (
    <div>
      <Head>
        <title>Kiran Methuku's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavigationBar/>
        <Intro/>
        <About/>
        <Projects/>
        <Skills/>
        <Contact/>
      </main>

      <footer>
        Created with <img src="/heart.png" width="12" height="auto"/> by Kiran Methuku | © 2021
      </footer>
    </div>
  )
}

export default Home;